### ISSUE TITLE
Cannot install ChemmineOB

### ISSUE THREAD

**Issue by joannazbijewska** [girke-lab/ChemmineOB#11]
I've tried probably almost all possible ways to install the ChemmineOB package - from Bioconductor, through building via devtools, from github package and the way it is described in the install file in the original release. However, all the time I'm getting this error message:

"
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded
Error : .onLoad failed in loadNamespace() for 'ChemmineOB', details:
  call: dyn.load(file, DLLpath = DLLpath, ...)
  error: cannot load shared object  '/home/joanna/R/i686-pc-linux-gnu-library/3.3/ChemmineOB/libs/ChemmineOB.so':
  /home/joanna/R/i686-pc-linux-gnu-library/3.3/ChemmineOB/libs/ChemmineOB.so: undefined symbol: _ZN9OpenBabel11OBTypeTable9GetToTypeB5cxx11Ev
ERROR: loading failed
Execution halted
ERROR: loading failed
* removing ‘/home/joanna/R/i686-pc-linux-gnu-library/3.3/ChemmineOB’
"

I'm installing under Ubuntu 16.04 LTS.
Could you, please advise me some way to deal with it? I would love to use this package ASAP.

**Comment by khoran** [comment]
It cannot find the openbabel library most likely. If it's installed in a 
non-standard location (like in your home directory somewhere), you'll 
have to set some environment variables each time you use ChemmineOB (you 
could set them in your shell profile to load when you login if you 
want). First, find out where openbabel is installed, I'll refer to that 
directory as "<openbabel_dir>". Then set the following 3 environment 
variables:

export LD_LIBRARY_PATH=<openbabel_dir>/build/lib
export BABEL_LIBDIR=$LD_LIBRARY_PATH
export BABEL_DATADIR=<openbabel_dir>/data

The <openbabel_dir>/build/lib should have lots of *.so files and the 
<openbabel_dir>/data should have lots of *.txt and *.par files in it. 
Once these environment variables are set you should be able to install 
and use ChemmineOB.

Kevin
