### ISSUE TITLE
regenerateCoords fails in ChemmineR vignette

### ISSUE THREAD

**Issue by jarrodscott** [girke-lab/ChemmineOB#20]
Hello 

I am following the tutorial ~[here](http://girke.bioinformatics.ucr.edu/manuals/vignettes/ChemmineR/ChemmineR.html#format-interconversions)~ in `vignette("ChemmineR")` and when I get to the part on   **OpenBabel Functions** and run this command:

`sdfset2 = regenerateCoords(sdfset[1:5])` I get this error:

`Error in convertFormat("SDF", "SDF", defs, options) :   unused argument (options)`

the following command yields the same error.

`plot(sdfset[1], regenCoords=TRUE,print=FALSE)`
I have search high and low for a cause. maybe it's my version of openbabel? I tried installing v2.3.2 but that failed. 

I am running:
on `Mac OSX, 10.15.2`
`ChemmineOB_1.2.9` 
`ChemmineR_3.36.0`
`openbabel-2.4.1`

I am also cross-posting on ChemmineR. 

Thanks!

**Comment by jarrodscott** [comment]
Ps I should add that the command works with `regenCoords=FALSE`

**Comment by khoran** [comment]
This was caused by the ChemmineOB version being too old. The 'options' argument was added in version 1.3.7. In general though, you should use the latest available version of both ChemmineR and ChemmineOB together.
