### ISSUE TITLE
Hardwired dependency on openbabel v2

### ISSUE THREAD

**Issue by eddelbuettel** [girke-lab/ChemmineOB#21]
I am trying to install BioMedR (to check it as a reverse depedency of Rcpp) but run into issues as I only have OpenBabel 3.0 on Ubuntu 19.10, and ChemmineOB will not install -- `rand.h` for example is no longer present.

Any chance you could update ChemmineOB to work with this current version of OpenBabel?

/cc @mtmorgan who may have another idea as he often does...

**Comment by khoran** [comment]
I have been working on the update to OpenBabel 3.0 recently. I should have a development version deployed either by the end of today, or next week sometime.

**Comment by eddelbuettel** [comment]
Sounds good.  

And my more immediate issue was solved at the BioConductor side with a new package no longer having the dependency that lead to a dependency on your package.
