### ISSUE TITLE
Install problems

### ISSUE THREAD

**Issue by dziessner** [girke-lab/ChemmineOB#24]
Hello

I've been having trouble installing since updating to R 4.0 and openbabel 3.1.0. ChemmineOB worked great on previous versions. ChemmineR does not seem to have a problem with the new versions.

I changed the library and include paths, and that changed my errors. Now I get one that says 

ChemmineOB.cpp:1501:10: fatal error: openbabel/atomclass.h: No such file or directory
 #include <openbabel/atomclass.h>

I searched for atomclass.h and don't seem to have that file anywhere (I deleted old versions of openbabel but can reinstall if that would solve it.)

Any help is appreciated.

**Comment by khoran** [comment]
What version of ChemmineOB were you using? If it was the release version (1.26.x), it will not be compatible with OpenBabel 3.x yet. You can download a compatible development version (1.25.2) from [here](https://github.com/girke-lab/ChemmineOB/releases/tag/1.25.2) for now.

**Comment by dziessner** [comment]
This worked, thank you for your response!
