### ISSUE TITLE
ChemmineOB install trouble

### ISSUE THREAD

**Issue by kenlo1** [girke-lab/ChemmineOB#25]
Hi all, 

I am having some issues installing ChemmineOB on CentOS 7.  

Basically I don't have root access and have installed openbabel in a custom directory using cmake flags
-DCMAKE_INSTALL_PREFIX and -DEIGEN3_INCLUDE_DIR

Since I am using custom paths, I used this to install ChemmineOB.
R CMD INSTALL --configure-args='--with-openbabel-include=/nfs/peptide/software/openbabel/include/openbabel3 --with-openbabel-lib=/nfs/peptide/software/openbabel/lib' ./ChemmineOB_1.28.4.tar.gz

Here is what the error message says:
---------------------------------------------
* installing to library ‘/nfs/peptide/home/lok2/bin/R-3.6.3/library’
* installing *source* package ‘ChemmineOB’ ...
** using staged installation
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for gcc... gcc -std=gnu99
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc -std=gnu99 accepts -g... yes
checking for gcc -std=gnu99 option to accept ISO C89... none needed
checking how to run the C preprocessor... gcc -std=gnu99 -E
configure: creating ./config.status
config.status: creating src/Makevars
** libs
g++ -std=gnu++11 -I"/home/lok2/bin/R-3.6.3/include" -DNDEBUG -I/usr/include/openbabel3  -I/usr/include/eigen3  -DUSE_BOOST -DHAVE_EIGEN  -I/usr/local/Cellar/eigen/3.3.8_1/include/eigen3 -I/usr/local/Cellar/open-babel/3.1.1_1/include/openbabel3  -I/nfs/peptide/software/openbabel/include/openbabel3  -I"/nfs/peptide/home/lok2/bin/R-3.6.3/library/BH/include" -I"/nfs/peptide/home/lok2/bin/R-3.6.3/library/Rcpp/include" -I/usr/local/include  -fpic  -g -O2  -c ChemmineOB.cpp -o ChemmineOB.o
In file included from ChemmineOB.cpp:1624:0:
/nfs/peptide/software/openbabel/include/openbabel3/openbabel/math/align.h:26:22: fatal error: Eigen/Core: No such file or directory
 #include <Eigen/Core>
                      ^
compilation terminated.
make: *** [ChemmineOB.o] Error 1
ERROR: compilation failed for package ‘ChemmineOB’
* removing ‘/nfs/peptide/home/lok2/bin/R-3.6.3/library/ChemmineOB’
------------------------------------------------

It seems like it is not finding Eigen, then I noticed that -I/usr/inlcude/eigen3, which is not where I have eigen3.  Is there an install flag that can change this?  My eigen3 is in /usr/local/include/eigen3.

Any help would be awesome.

Best,

Ken

**Comment by khoran** [comment]
You can add additional directories by setting some environment variables for the compiler. One way to do this is by creating the file ~/.R/Makevars and setting `CXXFLAGS= -I /usr/local/include/eigen3` . If that doesn't modify the compile command, try using `PKG_CXXFLAGS`.

**Comment by kenlo1** [comment]
Thanks! I was able to get past that first error.  Now my error message reads as follows:

R CMD INSTALL --configure-args='--with-openbabel-include=/nfs/peptide/software/openbabel/include/openbabel3 --with-openbabel-lib=/nfs/peptide/software/openbabel/lib' ./ChemmineOB_1.28.4.tar.gz
* installing to library ‘/nfs/peptide/home/lok2/bin/R-3.6.3/library’
* installing *source* package ‘ChemmineOB’ ...
** using staged installation
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for gcc... gcc -std=gnu99
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc -std=gnu99 accepts -g... yes
checking for gcc -std=gnu99 option to accept ISO C89... none needed
checking how to run the C preprocessor... gcc -std=gnu99 -E
configure: creating ./config.status
config.status: creating src/Makevars
** libs
g++ -std=gnu++11 -I"/home/lok2/bin/R-3.6.3/include" -DNDEBUG -I/usr/include/openbabel3  -I/usr/include/eigen3  -DUSE_BOOST -DHAVE_EIGEN  -I/usr/local/Cellar/eigen/3.3.8_1/include/eigen3 -I/usr/local/Cellar/open-babel/3.1.1_1/include/openbabel3  -I/nfs/peptide/software/openbabel/include/openbabel3  -I"/nfs/peptide/home/lok2/bin/R-3.6.3/library/BH/include" -I"/nfs/peptide/home/lok2/bin/R-3.6.3/library/Rcpp/include" -I/usr/local/include  -fpic  -I/usr/local/include/eigen-3.2.10 -c ChemmineOB.cpp -o ChemmineOB.o
g++ -std=gnu++11 -I"/home/lok2/bin/R-3.6.3/include" -DNDEBUG -I/usr/include/openbabel3  -I/usr/include/eigen3  -DUSE_BOOST -DHAVE_EIGEN  -I/usr/local/Cellar/eigen/3.3.8_1/include/eigen3 -I/usr/local/Cellar/open-babel/3.1.1_1/include/openbabel3  -I/nfs/peptide/software/openbabel/include/openbabel3  -I"/nfs/peptide/home/lok2/bin/R-3.6.3/library/BH/include" -I"/nfs/peptide/home/lok2/bin/R-3.6.3/library/Rcpp/include" -I/usr/local/include  -fpic  -I/usr/local/include/eigen-3.2.10 -c canonical.cpp -o canonical.o
g++ -std=gnu++11 -shared -L/usr/local/lib64 -o ChemmineOB.so ChemmineOB.o canonical.o -L/usr/local/Cellar/open-babel/3.1.1_1/lib -L/nfs/peptide/software/openbabel/lib -lopenbabel
installing to /nfs/peptide/home/lok2/bin/R-3.6.3/library/00LOCK-ChemmineOB/00new/ChemmineOB/libs
** R
** inst
** byte-compile and prepare package for lazy loading
in method for ‘copyToR’ with signature ‘"_p_std::char_traits<(char)>"’: no definition for class “_p_std::char_traits<(char)>”
in method for ‘copyToR’ with signature ‘"_p_std::pair<(unsigned int,unsigned int)>"’: no definition for class “_p_std::pair<(unsigned int,unsigned int)>”
in method for ‘copyToR’ with signature ‘"_p_OpenBabel::CharPtrLess"’: no definition for class “_p_OpenBabel::CharPtrLess”
in method for ‘copyToR’ with signature ‘"_p_OpenBabel::FptIndexHeader"’: no definition for class “_p_OpenBabel::FptIndexHeader”
in method for ‘copyToR’ with signature ‘"_p_OpenBabel::OBStereo"’: no definition for class “_p_OpenBabel::OBStereo”
in method for ‘copyToR’ with signature ‘"_p_OpenBabel::OBStereoUnit"’: no definition for class “_p_OpenBabel::OBStereoUnit”
in method for ‘copyToR’ with signature ‘"_p_OpenBabel::LineSearchType"’: no definition for class “_p_OpenBabel::LineSearchType”
in method for ‘copyToR’ with signature ‘"_p_OpenBabel::OBTetrahedralConfig"’: no definition for class “_p_OpenBabel::OBTetrahedralConfig”
in method for ‘copyToR’ with signature ‘"_p_OpenBabel::OBCisTransConfig"’: no definition for class “_p_OpenBabel::OBCisTransConfig”
in method for ‘copyToR’ with signature ‘"_p_OpenBabel::OBSquarePlanarConfig"’: no definition for class “_p_OpenBabel::OBSquarePlanarConfig”
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded from temporary location
Error: package or namespace load failed for ‘ChemmineOB’:
 .onLoad failed in loadNamespace() for 'ChemmineOB', details:
  call: dyn.load(file, DLLpath = DLLpath, ...)
  error: unable to load shared object '/nfs/peptide/home/lok2/bin/R-3.6.3/library/00LOCK-ChemmineOB/00new/ChemmineOB/libs/ChemmineOB.so':
  libopenbabel.so.7: cannot open shared object file: No such file or directory
Error: loading failed
Execution halted
ERROR: loading failed
* removing ‘/nfs/peptide/home/lok2/bin/R-3.6.3/library/ChemmineOB’

**Comment by khoran** [comment]
Set these two environment variables (see INSTALL file):
```
OPEN_BABEL_INCDIR = path to header files
OPEN_BABEL_LIBDIR = path to shared (.so) library file
```

**Comment by kenlo1** [comment]
Does that mean the --configure-args switch does not achieve the same thing?

**Comment by kenlo1** [comment]
I noticed this in the error message:

libopenbabel.so.7: cannot open shared object file: No such file or directory

I'm not sure if this is relevant, but in the directory specified with the '--with-openbabel-lib' flag, I am seeing libopenbabel.so.7, so that is a little curious.

**Comment by khoran** [comment]
--configure-args and --with-openbabel-lib are for compile time. But R still needs to know where the library is at runtime. So anytime you want to use the ChemmineOB package, the `OPEN_BABEL_*` environment variables need to be defined. This is easily accomplished by putting them in your .bashrc file or whatever config file your shell uses.

**Comment by kenlo1** [comment]
I added to environment variables as per your suggestion.  This is what I see when I check the environment variables.

>echo $OPEN_BABEL_INCDIR
/nfs/peptide/software/openbabel/include/openbabel3

>echo $OPEN_BABEL_LIBDIR
/nfs/peptide/software/openbabel/lib

I tried installing again with R CMD INSTALL --configure-args='--with-openbabel-include=/nfs/peptide/software/openbabel/include/openbabel3 --with-openbabel-lib=/nfs/peptide/software/openbabel/lib' ./ChemmineOB_1.28.4.tar.gz

but I still get the same error message.

**Comment by kenlo1** [comment]
Hi Kevin, 

I figured out what was wrong.  It turns out that my LD_LIBRARY_PATH environment variable wasn't set correctly.  I found some additional information from open-babel (https://open-babel.readthedocs.io/en/latest/Installation/install.html#environment-variables).  Once I changed it to the correct location, ChemmineOB installed correctly.   Thanks for all your help!

Best,

Ken
