### ISSUE TITLE
ChemmineOB installation failed

### ISSUE THREAD

**Issue by AgnieszkaGajewicz** [girke-lab/ChemmineOB#26]
I'm having problems loading ChemmineOB and repeatedly get this error:

Error: package or namespace load failed for ‘ChemmineOB’:
 .onLoad failed in loadNamespace() for 'ChemmineOB', details:
  call: dyn.load(file, DLLpath = DLLpath, ...)
  error: unable to load shared object '/Library/Frameworks/R.framework/Versions/4.1/Resources/library/ChemmineOB/libs/ChemmineOB.so':
  dlopen(/Library/Frameworks/R.framework/Versions/4.1/Resources/library/ChemmineOB/libs/ChemmineOB.so, 10): Library not loaded: /usr/local/opt/open-babel/lib/libopenbabel.7.dylib
  Referenced from: /Library/Frameworks/R.framework/Versions/4.1/Resources/library/ChemmineOB/libs/ChemmineOB.so
  Reason: image not found

I'm on macOS Big Sur and R version 4.1.2 (2021-11-01) - is there something I'm missing? I would be grateful for any help.

**Comment by tgirke** [comment]
For debugging your installation of the OB and the package, please follow the instructions in the INSTALL page [here](https://bit.ly/34hd6Et).
