### ISSUE TITLE
InChI not generated on windows version

### ISSUE THREAD

**Issue by Aariq** [girke-lab/ChemmineOB#37]
On a GitHub actions windows runner, it looks like InChI keys aren't generated by `ChemmineR::propOB()`.  I'm opening the issue *here* though because the OpenBabel warning that bubbles up says 

```
==============================
*** Open Babel Error  in GetStringValue
  InChIFormat is not loaded
==============================
```

which makes me think it has something to do with the bundled OpenBabel installation for the windows version of `ChemmineOB`.

**Comment by stanstrup** [comment]
maybe related to https://github.com/girke-lab/ChemmineOB/issues/9

**Comment by Aariq** [comment]
> maybe related to #9

Thanks.  So looks like maybe this is a known issue and not likely to be fixed?

**Comment by khoran** [comment]
Yes, unfortunately, this is a known limitation of the Windows version and cannot be fixed.
