### ISSUE TITLE
ChemmineOB doesn't compile with newer versions of openbabel

### ISSUE THREAD

**Issue by Kupac** [girke-lab/ChemmineOB#42]
It's more like a heads-up: Openbabel [has changed](https://github.com/openbabel/openbabel/commit/305a6fd3183540e4a8ae1d79d10bf1860e6aa373) the shared pointers, and ChemmineOB doesn't compile with the dev version of the library.

As the latest release (3.1.1) was more than four years ago, it's likely that many OS-es will move to a dev version. NixOS already did, which is how i found out about this.

> refactor: replace `obsharedptr` with `std::shared_ptr`

**Comment by khoran** [comment]
I understand your predicament. However, this is not something we can address right now. BioConductor is using 3.1.1, so our packages must build with that. I don't know if this change is backward compatible. When OpenBabel releases a new stable version, we can update ChemmineOB to work with it.
