### ISSUE TITLE
make inchi strings available on windows

### ISSUE THREAD

**Issue by khoran** [girke-lab/ChemmineOB#9]
requires either making a dynamic lib work on windows or forcing the inchi shared lib to be included in the static lib via symbol name mangling. Either method will take a long time and be very painful.

**Comment by stanstrup** [comment]
Hi. 
@TylerBackman I almost forgot our conversation in Dublin. You mentioned that it would be possible to have this fallback to pulling it from your online service or something like that?

**Comment by TylerBackman** [comment]
@stanstrup I added a feature to ChemMine Tools to generate InChI keys, which you can use directly with the ChemmineR ChemMine Tools interface. This doesn't overload the chemmineOB feature, but you can now use it immediately, without updating your R packages, as the feature options are grabbed remotely by ChemmineR.

Here is a code example:

`library(ChemmineR)
data(sdfsample)
sdf <- sdfsample
job <- launchCMTool('InChI Strings',sdf)
inchiResult <- result(job)`

The full API is documented here:
https://www.bioconductor.org/packages/release/bioc/vignettes/ChemmineR/inst/doc/ChemmineR.html#chemmine-tools-r-interface

**Comment by stanstrup** [comment]
Thanks!
Would it also be possible to get InChIKeys?
In the RMassBank project I referenced above I think that is what they need to get rid of direct calls to openbabel.

**Comment by TylerBackman** [comment]
@stanstrup, I have now added InChIkeys.

**Comment by stanstrup** [comment]
Fantastic! Thanks. I'll pass it along.
